function [ feaInd]=featureSelection( TrainMat, target )

maxdev = chi2inv(.95,1);     
opt = statset('display','iter',...
              'TolFun',maxdev,...
              'TolTypeFun','abs');

feaInd = sequentialfs(@critfun,TrainMat,target,...
                       'cv','none',...
                       'nullmodel',true,...
                       'options',opt,...
                       'direction','forward');


                   