gc()
Data3 = read.csv("/Users/kaili/Stevens/627BigData/HW2/EE627A_HW2_Q3.csv",header=F)
head(Data3)
Data3pro<-diff(Data3$V1)
dev.new()
par(mfrow=c(2,1))
plot.ts(Data3[,1])
plot.ts(Data3pro)
dev.new()
par(mfrow=c(1,2))
acf(Data3pro)
pacf(Data3pro)

q2<- arima(Data3,c(2,1,2))
q3<- arima(Data3,c(3,1,2))
q4<- arima(Data3,c(4,1,2))
dev.new()
par(mfrow=c(3,2))
acf(q2$residuals)
pacf(q2$residuals)
acf(q3$residuals)
pacf(q3$residuals)
acf(q4$residuals)
pacf(q4$residuals)

p2<- arima(Data3,c(3,1,1))
p3<- arima(Data3,c(3,1,2))
p4<- arima(Data3,c(3,1,3))
dev.new()
par(mfrow=c(3,2))
acf(p2$residuals)
pacf(p2$residuals)
acf(p3$residuals)
pacf(p3$residuals)
acf(p4$residuals)
pacf(p4$residuals)
pacf(tt5$residuals)



